# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1laiPK2frS3EbHTQOiNE7Zwt6l-RSFwRH
"""

pip install streamlit

pip install tensorflow streamlit pyngrok pillow numpy opencv-python

from google.colab import files
uploaded = files.upload()

import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image

st.title("🌿 AgroDetect AI – Plant Disease Detection")

model = tf.keras.models.load_model("agrodetect_model.keras")

class_names = ["Apple Scab","Apple Black Rot","Corn Rust","Healthy"]

def preprocess_image(image):
    image = image.resize((224, 224))
    img = np.array(image) / 255.0
    return np.expand_dims(img, axis=0)

uploaded = st.file_uploader("Upload leaf image", type=["jpg","png","jpeg"])

if uploaded:
    image = Image.open(uploaded)
    st.image(image, width=300)

    img = preprocess_image(image)
    pred = model.predict(img)

    class_id = np.argmax(pred)
    confidence = np.max(pred)

    st.subheader(f"🌱 Predicted: {class_names[class_id]}")
    st.write(f"Confidence: {confidence*100:.2f}%")